[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Change cash-out easing on Corrupt Green Deck
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "ease_dollars(G.GAME.current_round.dollars)"
position = "at"
payload = '''
if not G.GAME.in_corrupt_green then
  ease_dollars(G.GAME.current_round.dollars)
else
  Ovn_f.ease_complex_dollars(G.GAME.current_round.dollars, G.GAME.current_round.dollars_i)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.GAME.previous_round.dollars = G.GAME.dollars"
position = "after"
payload = "G.GAME.previous_round.dollars_i = G.GAME.dollars_i"
match_indent = true

# Display complex cost in Corrupt Green Deck
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
local t1 = {
    n=G.UIT.ROOT, config = {minw = 0.6, align = 'tm', colour = darken(G.C.BLACK, 0.2), shadow = true, r = 0.05, padding = 0.05, minh = 1}, nodes={
        {n=G.UIT.R, config={align = "cm", colour = lighten(G.C.BLACK, 0.1), r = 0.1, minw = 1, minh = 0.55, emboss = 0.05, padding = 0.03}, nodes={
          {n=G.UIT.O, config={object = DynaText({string = {{prefix = localize('$'), ref_table = card, ref_value = 'cost'}}, colours = {G.C.MONEY},shadow = true, silent = true, bump = true, pop_in = 0, scale = 0.5})}},
        }}
    }}
'''
position = "after"
payload = '''
if G.GAME.in_corrupt_green then
  t1.nodes[1].nodes[1].config.object:remove()
  t1 = {
      n=G.UIT.ROOT, config = {minw = 0.6, align = 'tm', colour = darken(G.C.BLACK, 0.2), shadow = true, r = 0.05, padding = 0.05, minh = 1}, nodes={
          {n=G.UIT.R, config={align = "cm", colour = lighten(G.C.BLACK, 0.1), r = 0.1, minw = 1, minh = 0.55, emboss = 0.05, padding = 0.03}, nodes={
            {n=G.UIT.O, config={object = DynaText({string = {{prefix = localize('$'), ref_table = card.ability, ref_value = 'complex_cost_label'}}, colours = {G.C.MONEY},shadow = true, silent = true, bump = true, pop_in = 0, scale = 0.5})}},
          }}
      }}
end
'''
match_indent = true

# Fix for loading shop cards not displaying complex costs in Corrupt Green Deck
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "create_shop_card_ui(v)" # Multi-target
position = "before"
payload = "Ovn_f.set_complex_cost_labels(v)"
match_indent = true

# Spend complex money when buying in Corrupt Green Deck
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
if c1.cost ~= 0 then
  ease_dollars(-c1.cost)
end
'''
position = "at"
payload = '''
if not G.GAME.in_corrupt_green then
  if c1.cost ~= 0 then
    ease_dollars(-c1.cost)
  end
else
  local cost, cost_i = Ovn_f.get_complex_cost(c1)
  Ovn_f.ease_complex_dollars(-cost, -cost_i or 0)
end
'''

match_indent = true

# Sell button displays complex cost on Corrupt Green Deck
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
sell = {n=G.UIT.C, config={align = "cr"}, nodes={
  {n=G.UIT.C, config={ref_table = card, align = "cr",padding = 0.1, r=0.08, minw = 1.25, hover = true, shadow = true, colour = G.C.UI.BACKGROUND_INACTIVE, one_press = true, button = 'sell_card', func = 'can_sell_card'}, nodes={
    {n=G.UIT.B, config = {w=0.1,h=0.6}},
    {n=G.UIT.C, config={align = "tm"}, nodes={
      {n=G.UIT.R, config={align = "cm", maxw = 1.25}, nodes={
        {n=G.UIT.T, config={text = localize('b_sell'),colour = G.C.UI.TEXT_LIGHT, scale = 0.4, shadow = true}}
      }},
      {n=G.UIT.R, config={align = "cm"}, nodes={
        {n=G.UIT.T, config={text = localize('$'),colour = G.C.WHITE, scale = 0.4, shadow = true}},
        {n=G.UIT.T, config={ref_table = card, ref_value = 'sell_cost_label',colour = G.C.WHITE, scale = 0.55, shadow = true}}
      }}
    }}
  }},
}}
'''
position = "after"
payload = '''
if G.GAME.in_corrupt_green then
  sell = {n=G.UIT.C, config={align = "cr"}, nodes={
    {n=G.UIT.C, config={ref_table = card, align = "cr",padding = 0.1, r=0.08, minw = 1.25, hover = true, shadow = true, colour = G.C.UI.BACKGROUND_INACTIVE, one_press = true, button = 'sell_card', func = 'can_sell_card'}, nodes={
      {n=G.UIT.B, config = {w=0.1,h=0.6}},
      {n=G.UIT.C, config={align = "tm"}, nodes={
        {n=G.UIT.R, config={align = "cm", maxw = 1.25}, nodes={
          {n=G.UIT.T, config={text = localize('b_sell'),colour = G.C.UI.TEXT_LIGHT, scale = 0.4, shadow = true}}
        }},
        {n=G.UIT.R, config={align = "cm"}, nodes={
          {n=G.UIT.T, config={text = localize('$'),colour = G.C.WHITE, scale = 0.4, shadow = true}},
          {n=G.UIT.T, config={ref_table = card.ability, ref_value = 'complex_sell_label',colour = G.C.WHITE, scale = 0.55, shadow = true}}
        }}
      }}
    }},
  }}
end
'''
match_indent = true

# Sell button eases complex dollars on Corrupt Green Deck
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "ease_dollars(self.sell_cost)"
position = "at"
payload = '''
if G.GAME.in_corrupt_green then
  local sell_cost, sell_i = Ovn_f.get_complex_sell_cost(self)
  Ovn_f.ease_complex_dollars(sell_cost, sell_i)
else
  ease_dollars(self.sell_cost)
end
'''
match_indent = true

# Redeeming Vouchers/opening booster packs eases complex dollars on Corrupt Green Deck
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "ease_dollars(-self.cost)"
position = "at"
payload = '''
if G.GAME.in_corrupt_green then
  local cost, cost_i = Ovn_f.get_complex_cost(self)
  Ovn_f.ease_complex_dollars(-cost, -cost_i)
else
  ease_dollars(-self.cost)
end
'''
match_indent = true