[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# lovely/corrupt_erratic_deck.toml
# used for crt replacement primarily

# [[patches]]
# [patches.pattern]
# target = 'game.lua'
# pattern = '''love.graphics.setShader( G.SHADERS['CRT'])'''
# position = "after"
# payload = '''
# if G.GAME and G.GAME.override_crt then
#     G.SHADERS['ovn_crt_override']:send("iTime", -G.TIMERS.REAL)
#     G.SHADERS['ovn_crt_override']:send("resolution", {love.graphics.getWidth(), love.graphics.getHeight()})
#     G.SHADERS['ovn_crt_override']:send("matrix_intensity", G.GAME.erratic_fx_matrix_intensity or 0)
#     G.SHADERS['ovn_crt_override']:send("matrix_lines", G.GAME.erratic_fx_matrix_lines or 30)
#     G.SHADERS['ovn_crt_override']:send("block_size", G.GAME.erratic_fx_block_size or 8)
#     G.SHADERS['ovn_crt_override']:send("block_offset", G.GAME.erratic_fx_block_offset or 10)
#     G.SHADERS['ovn_crt_override']:send("block_probability", G.GAME.erratic_fx_block_probability or 0.2)
#     G.SHADERS['ovn_crt_override']:send("matrix_color", G.GAME.erratic_fx_matrix_colour or {0.2, 1, 0.2, 0})
#     G.SHADERS['ovn_crt_override']:send("actually_mess_shit_up", Oblivion.config.disable_c_erratic_shader and 0 or 1)
#     love.graphics.setShader(G.SHADERS['ovn_crt_override'])
# end
# '''
# match_indent = true

# ----

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
{n=G.UIT.T, config={text = number_format(blind_amt), scale = score_number_scale(0.9, blind_amt), colour = disabled and G.C.UI.TEXT_INACTIVE or G.C.RED, shadow =  not disabled}}
'''
position = "before"
payload = '''
G.GAME.c_erratic and
SMODS.localize_box(loc_parse_string("{C:red,E:ovn_c_erratic_desc}????"), {scale=score_number_scale(0.9,6666)/0.32})[1]
or
'''
match_indent = true