[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# lovely/game_variables.toml
# Addition of new game variables

# ----

# function G.FUNCS.evaluate_play
# Update last-played-hand tracker
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, after = true})"
position = "after"
payload = "Ovn_f.update_hands_last_played(text)"
match_indent = true

# ----

# function G.FUNCS.evaluate_play
# Note whether specific hands are played in a round
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)"
position = "after"
payload = '''
if disp_text == "Royal Flush" then
  G.GAME.current_round.played_royal_flush = true
end
if next(poker_hands["ovn_Straight Spectrum"]) then
  G.GAME.current_round.played_straight_spec = true
end
'''
match_indent = true

# ----

# function Card:set_ability
# This is a temporary SMODS fix that is present in latest SMODS dev
# and will be removed once new SMODS release is out
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability and not initial then
    self.ability.card_limit = self.ability.card_limit - (self.config.center.card_limit or 0)
    self.ability.extra_slots_used = self.ability.extra_slots_used - (self.config.center.extra_slots_used or 0)
    if self.area then self.area:handle_card_limit(-1 * (self.config.center.card_limit or 0), -1 * (self.config.center.extra_slots_used or 0)) end
end
'''
position = "at"
payload = '''
if self.ability and not initial then
    self.ability.card_limit = self.ability.card_limit - (self.config.center.config.card_limit or 0)
    self.ability.extra_slots_used = self.ability.extra_slots_used - (self.config.center.config.extra_slots_used or 0)
    if self.area then self.area:handle_card_limit(-1 * (self.config.center.config.card_limit or 0), -1 * (self.config.center.config.extra_slots_used or 0)) end
end
'''
match_indent = true
