[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Replace title Ace of Spades with Optics of Spades
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS.S_A, G.P_CENTERS.c_base)"
position = "at"
payload = '''
local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS['ovn_O'..'_'..'A'], G.P_CENTERS.c_base)
'''
match_indent = true

# Replace colors of title splash background
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "{name = 'colour_1', ref_table = G.C, ref_value = 'RED'},"
position = "at"
payload = '''
{name = 'colour_1', ref_table = G.C, ref_value = 'PURPLE'},
'''
match_indent = true

# Replace intro Jimbo with a random corrupted Joker
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_joker'])"
position = "at"
payload = '''
local replace = {}
			for _, v in pairs(Oblivion.corruption_map) do
				if G.P_CENTERS[v] then
					replace[#replace + 1] = v
				end
			end
 		local option = math.random(#replace)
   		local chosenoption = replace[option]
SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS[chosenoption],{bypass_discovery_center = true, bypass_discovery_ui = true})
'''
match_indent = true

# Optics' base chips are doubled
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if initial then self.base.original_value = self.base.value end
'''
position = "after"
payload = '''
self.ability.bonus = self.ability.bonus - (self.ability.ovn_optics_bonus or 0)
if self.base.suit == 'ovn_Optics' then
  self.ability.ovn_optics_bonus = self.base.nominal
  self.ability.bonus = self.ability.bonus + self.ability.ovn_optics_bonus
else
  self.ability.ovn_optics_bonus = 0
end
'''
match_indent = true

# Show tooltips for Joker corruptibility and Optics effect
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "for _, v in ipairs(info_queue) do"
position = "before"
payload = '''
if Ovn_f.joker_is_corruptible(_c.key) and _c.discovered then
  table.insert(info_queue, {
    key = 'ovn_corruptible',
    set = 'Other',
    vars = { localize {
      type = "name_text",
      set = "Joker",
      key = _c.key
    } }
  })
end

if card and card.base and card.base.suit == "ovn_Optics" then
  table.insert(info_queue, {
    key = 'ovn_opticinfo',
    set = 'Other',
  })
end
'''
match_indent = true

# Joker banishing, inspired by Cryptid
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.yes_pool_flag and not G.GAME.pool_flags[v.yes_pool_flag] then add = nil end"
position = "after"
payload = '''
if Ovn_f.is_corruptbanished(v.key) then add = nil end
if v.key == 'j_cavendish' and Ovn_f.has_joker('j_ovn_aeon') then add = true end
'''
match_indent = true

# Implementation of temporary hand size decreases
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.current_round.used_packs = {}"
position = "after"
payload = "G.GAME.current_round.temp_handsize_change = 0"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "reset_idol_card()"
position = "before"
payload = '''
G.hand:change_size(-G.GAME.current_round.temp_handsize_change)
G.GAME.current_round.temp_handsize_change = 0
'''
match_indent = true

# Instability is not changed when hand is parsed
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "update_hand_text({immediate = true, nopulse = true, delay = 0}, {[name] = parameter.default_value})"
position = 'at'
payload = '''if name ~= "ovn_instability" then
  update_hand_text({immediate = true, nopulse = true, delay = 0}, {[name] = parameter.default_value})
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "update_hand_text({delay = 0}, {[name] = parameter.default_value})"
position = 'at'
payload = '''if name ~= "ovn_instability" then
  update_hand_text({delay = 0}, {[name] = parameter.default_value})
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''for name, parameter in pairs(SMODS.Scoring_Parameters) do
    parameter.current = G.GAME.hands[text][name] or parameter.default_value
    update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = parameter.current})
end'''
position = 'at'
payload = '''for name, parameter in pairs(SMODS.Scoring_Parameters) do
  if name ~= "ovn_instability" then
    parameter.current = G.GAME.hands[text][name] or parameter.default_value
    update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = parameter.current})
  end
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = "update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = '?'})"
position = 'after'
payload = '''if name ~= "ovn_instability" then
  update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = '?'})
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "parameter.current = parameter.default_value"
position = 'at'
payload = '''if name ~= "ovn_instability" then
  parameter.current = parameter.default_value
end'''
match_indent = true

# Migraine makes all standard pack cards Optics
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "card:start_materialize({G.C.WHITE, G.C.WHITE}, nil, 1.5*G.SETTINGS.GAMESPEED)"
position = "after"
payload = '''if Ovn_f.has_joker('j_ovn_migraine') and (card.ability.set == "Default" or card.ability.set == "Enhanced") then
  card:change_suit('ovn_Optics')
  Ovn_f.guaranteed_modifier(card, i)
end'''
match_indent = true

# Cigarette Card makes all Uncommons Miasma
# (This patch disables specifying editions in the above condition)
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "if t.edition then _card:set_edition(t.edition) end"
position = "at"
payload = '''if Ovn_f.has_joker('j_ovn_cigarette_card') and _card.config.center.rarity == 2 then
else
  if t.edition then _card:set_edition(t.edition) end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if not SMODS.bypass_create_card_edition and not card.edition then"
position = "before"
payload = '''if Ovn_f.has_joker('j_ovn_cigarette_card') and card.config.center.rarity == 2 then
  card:set_edition("e_ovn_miasma")
end'''
match_indent = true

# Update last-played-hand tracker
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, after = true})"
position = "after"
payload = "Ovn_f.update_hands_last_played(text)"
match_indent = true

# Corrupt background
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif G.GAME.won then
    ease_background_colour{new_colour = G.C.BLIND.won, contrast = 1}
elseif blindname == 'Small Blind' or blindname == 'Big Blind' or blindname == '' then
    ease_background_colour{new_colour = G.C.BLIND['Small'], contrast = 1}
'''
position = "at"
payload = '''elseif G.GAME.won and G.GAME.in_corrupt then
    ease_background_colour{new_colour = G.ARGS.LOC_COLOURS.ovn_corrupt2, contrast = 1}
elseif (blindname == 'Small Blind' or blindname == 'Big Blind' or blindname == '') and G.GAME.in_corrupt then
    ease_background_colour{new_colour = G.ARGS.LOC_COLOURS.ovn_corrupt1, contrast = 1}
elseif G.GAME.won and not G.GAME.in_corrupt then
    ease_background_colour{new_colour = G.C.BLIND.won, contrast = 1}
elseif (blindname == 'Small Blind' or blindname == 'Big Blind' or blindname == '') and not G.GAME.in_corrupt then
    ease_background_colour{new_colour = G.C.BLIND['Small'], contrast = 1}
'''
match_indent = true

# Fix for corrupt bg not appearing on run load
# might need to put "is_corrupt" as Back property
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if not saveTable then ease_background_colour_blind(G.STATE, 'Small Blind')"
position = "before"
payload = '''
local get_the_fucking_back = saveTable and saveTable.BACK.name or (args.challenge and args.challenge.deck and args.challenge.deck.type) or (self.GAME.viewed_back and self.GAME.viewed_back.name) or self.GAME.selected_back and self.GAME.selected_back.name or 'Red Deck'
if get_the_fucking_back:match('b_ovn_c_') then self.GAME.in_corrupt = true end
'''
match_indent = true

# Fix for corrupt bg not appearing on run load
# might need to put "is_corrupt" as Back property
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)"
position = "after"
payload = '''
if disp_text == "Royal Flush" then
  G.GAME.current_round.played_royal_flush = true
end
if next(poker_hands["ovn_Straight Spectrum"] then
  G.GAME.current_round.played_straight_spec = true
end
'''
match_indent = true

