[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# lovely/miscellaneous.toml

# ----

# function Card:remove_from_deck
# All-encompassing "card_removed" context
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == 'Stuntman' then
    G.hand:change_size(self.ability.extra.h_size)
end
'''
position = "after"
payload = '''
SMODS.calculate_context{ovn_card_removed = true, card = self, from_debuff = from_debuff}
'''
match_indent = true

# ----

# function CardArea:draw
# -inf text on Joker CardArea
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''
local card_count = self ~= G.shop_vouchers and {n=G.UIT.R, config={align = self == G.jokers and 'cl' or self == G.hand and 'cm' or 'cr', padding = 0.03, no_fill = true}, nodes={
    {n=G.UIT.B, config={w = 0.1,h=0.1}},
    {n=G.UIT.T, config={ref_table = self.config, ref_value = 'card_count', scale = 0.3, colour = G.C.WHITE}},
    {n=G.UIT.T, config={text = '/', scale = 0.3, colour = G.C.WHITE}},
    {n=G.UIT.T, config={ref_table = self.config, ref_value = 'true_card_limit', scale = 0.3, colour = G.C.WHITE}},
    {n=G.UIT.B, config={w = 0.1,h=0.1}}
}} or nil
'''
position = "after"
payload = '''
if self == G.jokers and Ovn_f.on_deck("c_painted") and card_count then
  card_count.nodes[4].config = {text='-inf', scale = 0.3, colour = G.C.WHITE}
end
'''
match_indent = true

# ----

# In Steamodded:
# function G.FUNCS.hand_type_UI_set
# Increase sigfigs for instability
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/ui.lua"]'''
pattern = '''
local new_mult_text = number_format(G.GAME.current_round.current_hand[e.config.type] or SMODS.Scoring_Parameters[e.config.type].default_value)
'''
position = "after"
payload = '''
local num = G.GAME.current_round.current_hand[e.config.type] or SMODS.Scoring_Parameters[e.config.type].default_value

if (e.config.type == "ovn_instability") and (num <= 10) and (tonumber(("%.2f"):format(num)) ~= tonumber(("%.3f"):format(num))) then
  new_mult_text = ("%.3f"):format(num)
end
'''
match_indent = true

# ----

# function create_UIBox_blind_choice
# Makes blind requirement glitchy on Corrupt Erratic Deck
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
{n=G.UIT.T, config={text = number_format(blind_amt), scale = score_number_scale(0.9, blind_amt), colour = disabled and G.C.UI.TEXT_INACTIVE or G.C.RED, shadow =  not disabled}}
'''
position = "before"
payload = '''
G.GAME.c_erratic and
SMODS.localize_box(loc_parse_string("{C:red,E:ovn_glitched}????"), {scale=score_number_scale(0.9,6666)/0.32})[1]
or
'''
match_indent = true